/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32f401xe.h>
#include "systick.h"
#include "gpio.h"
#include "usart.h"
#include "myprintf.h"
#include "ota_update.h"


#define APP_ADDR 0x08020000
#define MAJOR 0
#define MINOR 1

static void goto_application(void);

const uint8_t BL_Version[2] = {MAJOR, MINOR};


int main(void)
{
	uint32_t current_tick = 0;
	GPIO_PIN_STATE OTA_PIN_State;

	systick_init();


	gpio_rcc(GPIOA);
	gpio_init(GPIOA, PIN5, OUTPUT);
	gpio_set(GPIOA, PIN5);


	myprintf_init();

	//gpioa_led5(); this is toggle mode

	myprintf("Starting Bootloader (%d.%d)\n", BL_Version[0], BL_Version[1]);

	myprintf("Press User Button to trigger OTA Update....\n");

	uint32_t nextTick = Get_Tick() + 3000;

	/*Check User button is pressed*/
	do
	{
		OTA_PIN_State = gpio_read_status(GPIOC, PIN13);
		current_tick = Get_Tick();


		/*Check User button state for 3 seconds*/
		if((OTA_PIN_State != GPIO_PIN_SET) || (current_tick > nextTick)){

			/*only when timeout or User button is pressed*/
			break;
		}
	}while(1);

	/*Start the Firmware or Application update*/
	if(OTA_PIN_State == GPIO_PIN_RESET){
		myprintf("Starting Firmware Download!!!\n");

		/*OTA Request, receive the data from UART2 and flash*/
		if(ota_download_and_flash() != OTA_EX_OK){

			/*Error*/
			myprintf("OTA Update: ERROR!!! HALT!!\n");
			while(1);
		}
		else{

			/*Reset to load new application*/
			myprintf("Firmware update is done!!! Rebooting...\n");
			NVIC_SystemReset();//Reset API from cmsis
		}
	}

	goto_application();


    /* Loop forever */
	while(1){



	};
}

static void goto_application(void){

	myprintf("Gonna Jump to Application\n");
	wait_empty_buff();

	void (*app_reset_handler)(void) = (void*)(*(volatile uint32_t*)(APP_ADDR + 4));

	SCB->VTOR = 0X08020000;

	__set_MSP(*(volatile uint32_t*)APP_ADDR);//this is from cmsis

	gpio_reset(GPIOA, PIN5);
	app_reset_handler();
}
