/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stm32f401xe.h>
#include "systick.h"
#include "myprintf.h"
#include "usart.h"
#include "gpio.h"
#include "ttys.h"

//Only when buffer is 4 can we use my printf properly. If buffer more than 5 please comment out myprintf() and related variable
#define MAJOR 0
#define MINOR 1

const uint32_t APP_Version[2] = {MAJOR, MINOR};

int main(void)
{
	myprintf_init();
	ttys_init();
	myprintf("Starting Application (%d.%d)\n", APP_Version[0], APP_Version[1]);

    while (1)
    {


    	ttys_run();



    }
}
